### ISSUE TITLE
Problems with programmatic data download

### ISSUE THREAD

**Issue by cthoyt** [OpenBioLink/OpenBioLink#42]
```python
from urllib.request import urlretrieve
url = 'https://samwald.info/res/OpenBioLink_2020_final/HQ_DIR.zip'
urlretrieve(url, 'test.zip')
```
results in 
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 510: Not Extended
```

Downloading it by copy+pasting the URL into the browser works fine. Are there some settings on your server that are problematic?

Either way, I would suggest hosting the data on an archival system like Zenodo or Figshare rather than a personal website, which isn't guaranteed long term support.

**Comment by matthias-samwald** [comment]
We have now switched to hosting the benchmark files on Zenodo (see #47 ), thanks for the suggestion!
