### ISSUE TITLE
Error while running baselines evaluation

### ISSUE THREAD

**Issue by robertanto** [OpenBioLink/OpenBioLink#50]
When running the baselines training I get the following error. 

```bash
bio-graph> python -m openbiolink train -m TransR_Pykeen -t .\data\HQ_UNDIR\train_test_data\train_sample.csv -s .\data\HQ_UNDIR\train_test_data\test_sample.csv

starting training
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 181334/181334 [00:32<00:00, 5515.83it/s]

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "bio-graph\openbiolink\__main__.py", line 14, in <module>
    main()
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "bio-graph\openbiolink\openBioLink.py", line 247, in train
    config=config,
  File "bio-graph\openbiolink\cli_helper.py", line 108, in train_and_evaluate
    e.train()
  File "bio-graph\openbiolink\evaluation\evaluation.py", line 99, in train
    pos_examples = self.save_remove_n_edges(pos_examples, len(pos_examples) - num_examples)
  File "bio-graph\openbiolink\evaluation\evaluation.py", line 525, in save_remove_n_edges
    drop_indices_candidates = random.sample(edges.index.values.tolist(), n)
  File "C:\ProgramData\Anaconda3\lib\random.py", line 321, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
```

**Comment by nomisto** [comment]
Sorry the readme of the training cli input didn't got updated: We've splitted up the positive and negative edges into seperate files recently. The current state of the models require negative samples, so the new command of starting training and evaluation is:
 
```python -m openbiolink train -m TransR_Pykeen -s  .\data\HQ_UNDIR\train_test_data\train_sample.csv -ns  .\data\HQ_UNDIR\train_test_data\negative_train_sample.csv -t .\data\HQ_UNDIR\train_test_data\test_sample.csv -ts .\data\HQ_UNDIR\train_test_data\negative_test_sample.csv```

Also the flags indicating the paths got mixed up, so it is -s for the training path and -t for the testing path.

Cheers
