### ISSUE TITLE
Problems when running HITS_AT_K metric

### ISSUE THREAD

**Issue by robertanto** [OpenBioLink/OpenBioLink#52]
When running the baselines evaluation of the HITS_AT_K metric : 
```bash
python -m openbiolink train -m TransR_Pykeen -s .\data\HQ_DIR\train_test_data\train_sample.csv -ns .\data\HQ_DIR\train_test_data\negative_train_sample.csv -t .\data\HQ_DIR\train_test_data\test_sample.csv -nt .\data\HQ_DIR\train_test_data\negative_test_sample.csv --metrics HITS_AT_K
```

I get the following error:

```bash 
starting training
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 119576/119576 [00:28<00:00, 4196.54it/s]
  0%|                                                                                                                             | 1/119576 [00:00<7:14:26,  4.59it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [10:28<00:00, 628.82s/it]
starting evaluation██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16376/16376 [10:27<00:00, 26.09it/s]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "bio-graph\OpenBioLink\src\openbiolink\__main__.py", line 14, in <module>
    main()
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "bio-graph\OpenBioLink\src\openbiolink\openBioLink.py", line 247, in train
    config=config,
  File "bio-graph\OpenBioLink\src\openbiolink\cli_helper.py", line 120, in train_and_evaluate
    e.evaluate(metrics=metrics_to_use, ks=int_ks)
  File "bio-graph\OpenBioLink\src\openbiolink\evaluation\evaluation.py", line 133, in evaluate
    metrics=metrics, ks=ks, filtered_setting=filtered_options, unfiltered_setting=unfiltered_options
  File "bio-graph\OpenBioLink\src\openbiolink\evaluation\evaluation.py", line 251, in evaluate_ranked_metrics_2
    nodes_array = self.nodes.values
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by nomisto** [comment]
Hi, sorry for the amount of errors you get, we should definately work more on error handling and documentation.
When using ranked metrics, like hits @ k, you have to provide the nodes file of the train set. This is admittedly a little hidden specified in the help of train `python -m openbiolink train --help`.

So in order to make it work you will have to run:

```bash
python -m openbiolink train -m TransR_Pykeen -s .\data\HQ_DIR\train_test_data\train_sample.csv -ns .\data\HQ_DIR\train_test_data\negative_train_sample.csv -t .\data\HQ_DIR\train_test_data\test_sample.csv -nt .\data\HQ_DIR\train_test_data\negative_test_sample.csv --eval-nodes .\data\HQ_DIR\train_test_data\train_val_nodes.csv --metrics HITS_AT_K
```
