### ISSUE TITLE
Pass nodes type info to the train method

### ISSUE THREAD

**Issue by robertanto** [OpenBioLink/OpenBioLink#54]
An algorithm may benefit from the information about the type of the nodes involved in a triple.

It may be useful to pass this info to the training method.

**Comment by nomisto** [comment]
Closed with 28f500d3ef7d71ec1d231b6f4b18787e106de67b 29819cbec85dd44719432ca26a50847995d43bfb

Thanks for your suggestions!

I added the argument mapped_nodes to the train function, a 2D array which maps all node ID's to node-type ID's. The corresponding types to these ID's can be looked up in the generated json file.

**Comment by robertanto** [comment]
I am trying to run the following command with the updated version of your code.

```bash 
python -m openbiolink train -m TransE_Pykeen -s .\data\HQ_DIR\train_test_data\train_sample.csv -ns .\data\HQ_DIR\train_test_data\negative_train_sample.csv -t .\data\HQ_DIR\train_test_data\test_sample.csv -nt .\data\HQ_DIR\train_test_data\negative_test_sample.csv -v .\data\HQ_DIR\train_test_data\val_sample.csv -nv .\data\HQ_DIR\train_test_data\negative_val_sample.csv
```

But I receive the following error:

```bash 

starting training
Ensuring same size (Positive/Negative)...
100%|█████████████████████████████████████████████████████████████████████████████| 119576/119576 [00:27<00:00, 4378.88it/s]
  0%|                                                                                  | 1/119576 [00:00<6:48:41,  4.88it/s]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "bio-graph\OpenBioLink\src\openbiolink\__main__.py", line 14, in <module>
    main()
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "bio-graph\OpenBioLink\src\openbiolink\openBioLink.py", line 251, in train
    config=config,
  File "bio-graph\OpenBioLink\src\openbiolink\cli_helper.py", line 112, in train_and_evaluate   
    e.train()
  File "bio-graph\OpenBioLink\src\openbiolink\evaluation\evaluation.py", line 122, in train     
    nodes = self.nodes.values
AttributeError: 'NoneType' object has no attribute 'values'
 ```

**Comment by nomisto** [comment]
You'll have to provide the nodes file with
```--eval-nodes .\data\HQ_DIR\train_test_data\train_val_nodes.csv```
This is the file where the type is stored. With the changes today I should probably make it required now.

**Comment by robertanto** [comment]
Thank you!
