### ISSUE TITLE
 error after updating file urls

### ISSUE THREAD

**Issue by mjsduncan** [OpenBioLink/OpenBioLink#76]
hi, this is a great project!
i updated urls for the GO annotation file and the drugcentral sql dump file (pull request #75).  i then get this header mismatch error:
```
$ openbiolink generate
...
 14%|████████▍                                                     | 3/22 [02:01<11:12, 35.41s/it]
Traceback (most recent call last):
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/bin/openbiolink", line 33, in <module>
    sys.exit(load_entry_point('openbiolink', 'console_scripts', 'openbiolink')())
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mozi/biosrc/OpenBioLink/src/openbiolink/openBioLink.py", line 131, in generate
    mes=mes,
  File "/home/mozi/biosrc/OpenBioLink/src/openbiolink/cli_helper.py", line 59, in create_graph
    graph_creator.create_input_files()
  File "/home/mozi/biosrc/OpenBioLink/src/openbiolink/graph_creation/graphCreation.py", line 124, in create_input_files
    in_data = reader.read_file()
  File "/home/mozi/biosrc/OpenBioLink/src/openbiolink/graph_creation/file_reader/csvReader.py", line 37, in read_file
    dtype=self.dtype,
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 864, in pandas._libs.parsers.TextReader._get_header
ValueError: Passed header names mismatches usecols
```
these are the files in **in_files**:
```
$ ll in_files/
total 261960
drwxrwxr-x 2 mozi mozi      4096 Dec 18 20:09 ./
drwxrwxr-x 4 mozi mozi      4096 Dec 18 20:07 ../
-rw-rw-r-- 1 mozi mozi    281745 Dec 18 20:09 DB_DisGeNet_mapping_disease_umls_do.csv
-rw-rw-r-- 1 mozi mozi   1525216 Dec 18 20:09 DB_ONTO_GO_IS_A_ontology.csv
-rw-rw-r-- 1 mozi mozi    150832 Dec 18 20:09 DB_ONTO_GO_PART_OF_ontology.csv
-rw-rw-r-- 1 mozi mozi     80212 Dec 18 20:09 DB_ONTO_mapping_GO_alt_id.csv
-rw-rw-r-- 1 mozi mozi 266189832 Dec 18 20:07 DB_STITCH_gene_drug.csv
```
any way to tell which file is causing the header mismatch?

**Comment by mjsduncan** [comment]
great, thanks & happy holidays!
