### ISSUE TITLE
--qual 'lq' gives an error

### ISSUE THREAD

**Issue by mjsduncan** [OpenBioLink/OpenBioLink#77]
but **--qual 'nq'** works

```
$ openbiolink generate --skip --qual 'lq'
Traceback (most recent call last):
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/bin/openbiolink", line 33, in <module>
    sys.exit(load_entry_point('openbiolink', 'console_scripts', 'openbiolink')())
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 1657, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 914, in make_context
    self.parse_args(ctx, args)
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 1370, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 2347, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/mozi/biosrc/bcbio/anaconda/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 2309, in process_value
    value = self.callback(ctx, self, value)
  File "/home/mozi/biosrc/OpenBioLink/src/openbiolink/openBioLink.py", line 53, in handle_quality
    return QualityType.get_quality_type(qual)
  File "/home/mozi/biosrc/OpenBioLink/src/openbiolink/graph_creation/types/qualityType.py", line 21, in get_quality_type
    raise ValueError(f"Invalid QualityType: {qual}")
ValueError: Invalid QualityType: lq
```

**Comment by nomisto** [comment]
Thanks for reporting! Should be fixed now
